In [1]:
SERVICE_KEY = '78577a466b6a686a3539434662496e'

In [11]:
SERVICE_KEY = '78577a466b6a686a3539434662496e'
URL = f'http://openapi.seoul.go.kr:8088/{SERVICE_KEY}/json/tbLnOpendataRtmsV/1/100/'
URL

'http://openapi.seoul.go.kr:8088/78577a466b6a686a3539434662496e/json/tbLnOpendataRtmsV/1/100/'

In [1]:
import requests 
import json 
import pandas as pd 

req = requests.get(URL)
req

NameError: name 'URL' is not defined

In [13]:
content = req.json()
# content
result = pd.DataFrame(content['tbLnOpendataRtmsV']['row'])
result

,ACC_YEAR,SGG_CD,SGG_NM,BJDONG_CD,BJDONG_NM,LAND_GBN,LAND_GBN_NM,BONBEON,BUBEON,BLDG_NM,...,OBJ_AMT,BLDG_AREA,TOT_AREA,FLOOR,RIGHT_GBN,CNTL_YMD,BUILD_YEAR,HOUSE_TYPE,REQ_GBN,RDEALER_LAWDNM
0,2024,11560,영등포구,10200,영등포동1가,1,대지,0121,0005,여의도리슈빌DS,...,20600,21.41,31.43,7.0,,,2020,오피스텔,중개거래,서울 영등포구
1,2024,11740,강동구,10900,천호동,1,대지,0090,0002,도우빌라,...,36700,48.69,46.66,-1.0,,,1991,연립다세대,중개거래,서울 강동구
2,2024,11320,도봉구,10800,도봉동,1,대지,0051,0012,중흥에스-클래스,...,55000,85.00,0.00,3.0,,,2004,아파트,중개거래,서울 도봉구
3,2024,11545,금천구,10200,독산동,1,대지,1006,0115,중앙하이빌1동2동,...,23000,28.68,14.88,4.0,,,2016,연립다세대,직거래,
4,2024,11590,동작구,10300,상도1동,1,대지,0419,0003,종로빌리지,...,40000,69.13,48.37,3.0,,,1991,연립다세대,중개거래,서울 강남구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024,11215,광진구,10300,구의동,1,대지,0035,0048,금화빌라,...,20000,38.18,24.90,1.0,,,1997,연립다세대,중개거래,서울 광진구
96,2024,11740,강동구,10700,암사동,1,대지,0414,0002,롯데캐슬퍼스트,...,112500,59.99,0.00,28.0,,,2008,아파트,중개거래,서울 강동구
97,2024,11410,서대문구,11900,북가좌동,1,대지,0371,0001,월드컵현대,...,81500,84.93,0.00,12.0,,,1998,아파트,중개거래,서울 서대문구
98,2024,11590,동작구,10700,사당동,1,대지,1133,0000,삼성래미안,...,134000,158.47,0.00,13.0,,,2003,아파트,중개거래,서울 동작구
99,2024,11440,마포구,10800,대흥동,1,대지,0012,0027,이대역 푸르지오 시티,...,24000,28.80,39.60,4.0,,,2013,오피스텔,중개거래,서울 마포구

In [15]:
URL = f'http://openapi.seoul.go.kr:8088/{SERVICE_KEY}/xml/tbLnOpendataRtmsV/1/5/'
URL

'http://openapi.seoul.go.kr:8088/78577a466b6a686a3539434662496e/xml/tbLnOpendataRtmsV/1/5/'

In [17]:
import requests
from bs4 import BeautifulSoup
import pandas as pd 

req = requests.get(URL)
soup = BeautifulSoup(req.content, 'lxml')
print(soup.prettify())

<?xml version="1.0" encoding="UTF-8"?>
<html>
 <body>
  <tblnopendatartmsv>
   <list_total_count>
    2550681
   </list_total_count>
   <result>
    <code>
     INFO-000
    </code>
    <message>
     정상 처리되었습니다
    </message>
   </result>
   <row>
    <acc_year>
     2024
    </acc_year>
    <sgg_cd>
     11560
    </sgg_cd>
    <sgg_nm>
     영등포구
    </sgg_nm>
    <bjdong_cd>
     10200
    </bjdong_cd>
    <bjdong_nm>
     영등포동1가
    </bjdong_nm>
    <land_gbn>
     1
    </land_gbn>
    <land_gbn_nm>
     대지
    </land_gbn_nm>
    <bonbeon>
     0121
    </bonbeon>
    <bubeon>
     0005
    </bubeon>
    <bldg_nm>
     여의도리슈빌DS
    </bldg_nm>
    <deal_ymd>
     20240130
    </deal_ymd>
    <obj_amt>
     20600
    </obj_amt>
    <bldg_area>
     21.41
    </bldg_area>
    <tot_area>
     31.430000
    </tot_area>
    <floor>
     7
    </floor>
    <right_gbn>
    </right_gbn>
    <cntl_ymd>
    </cntl_ymd>
    <build_year>
     2020
    </build_year>
    <house_type>
     오피스텔
    </house_type>
    <req_gbn>
     중개거래
    </req_gbn>
    <rdealer_lawdnm>
     서울 영등포구
    </rdealer_lawdnm>
   </row>
   <row>
    <acc_year>
     2024
    </acc_year>
    <sgg_cd>
     11740
    </sgg_cd>
    <sgg_nm>
     강동구
    </sgg_nm>
    <bjdong_cd>
     10900
    </bjdong_cd>
    <bjdong_nm>
     천호동
    </bjdong_nm>
    <land_gbn>
     1
    </land_gbn>
    <land_gbn_nm>
     대지
    </land_gbn_nm>
    <bonbeon>
     0090
    </bonbeon>
    <bubeon>
     0002
    </bubeon>
    <bldg_nm>
     도우빌라
    </bldg_nm>
    <deal_ymd>
     20240130
    </deal_ymd>
    <obj_amt>
     36700
    </obj_amt>
    <bldg_area>
     48.69
    </bldg_area>
    <tot_area>
     46.660000
    </tot_area>
    <floor>
     -1
    </floor>
    <right_gbn>
    </right_gbn>
    <cntl_ymd>
    </cntl_ymd>
    <build_year>
     1991
    </build_year>
    <house_type>
     연립다세대
    </house_type>
    <req_gbn>
     중개거래
    </req_gbn>
    <rdealer_lawdnm>
     서울 강동구
    </rdealer_lawdnm>
   </row>
   <row>
    <acc_year>
     2024
    </acc_year>
    <sgg_cd>
     11320
    </sgg_cd>
    <sgg_nm>
     도봉구
    </sgg_nm>
    <bjdong_cd>
     10800
    </bjdong_cd>
    <bjdong_nm>
     도봉동
    </bjdong_nm>
    <land_gbn>
     1
    </land_gbn>
    <land_gbn_nm>
     대지
    </land_gbn_nm>
    <bonbeon>
     0051
    </bonbeon>
    <bubeon>
     0012
    </bubeon>
    <bldg_nm>
     중흥에스-클래스
    </bldg_nm>
    <deal_ymd>
     20240130
    </deal_ymd>
    <obj_amt>
     55000
    </obj_amt>
    <bldg_area>
     85
    </bldg_area>
    <tot_area>
     0.000000
    </tot_area>
    <floor>
     3
    </floor>
    <right_gbn>
    </right_gbn>
    <cntl_ymd>
    </cntl_ymd>
    <build_year>
     2004
    </build_year>
    <house_type>
     아파트
    </house_type>
    <req_gbn>
     중개거래
    </req_gbn>
    <rdealer_lawdnm>
     서울 도봉구
    </rdealer_lawdnm>
   </row>
   <row>
    <acc_year>
     2024
    </acc_year>
    <sgg_cd>
     11545
    </sgg_cd>
    <sgg_nm>
     금천구
    </sgg_nm>
    <bjdong_cd>
     10200
    </bjdong_cd>
    <bjdong_nm>
     독산동
    </bjdong_nm>
    <land_gbn>
     1
    </land_gbn>
    <land_gbn_nm>
     대지
    </land_gbn_nm>
    <bonbeon>
     1006
    </bonbeon>
    <bubeon>
     0115
    </bubeon>
    <bldg_nm>
     중앙하이빌1동2동
    </bldg_nm>
    <deal_ymd>
     20240130
    </deal_ymd>
    <obj_amt>
     23000
    </obj_amt>
    <bldg_area>
     28.68
    </bldg_area>
    <tot_area>
     14.880000
    </tot_area>
    <floor>
     4
    </floor>
    <right_gbn>
    </right_gbn>
    <cntl_ymd>
    </cntl_ymd>
    <build_year>
     2016
    </build_year>
    <house_type>
     연립다세대
    </house_type>
    <req_gbn>
     직거래
    </req_gbn>
    <rdealer_lawdnm>
    </rdealer_lawdnm>
   </row>
   <row>
    <acc_year>
     2024
    </acc_year>
    <sgg_cd>
     11590
    </sgg_cd>
    <sgg_nm>
     동작구
    </sgg_nm>
    <bjdong_cd>
     10300
    </bjdong_cd>
    <bjdong_nm>
     상도1동
    </bjdong_nm>
    <land_gbn>
     1
    </land_gbn>
    <land_gbn_nm>
     대지
    </land_gbn_nm>
    <bonbeon>
     0419
    </bonbeon>
    <bubeon>
     0003
    </bubeon>
    <bldg_nm>
     종로빌리지
    </bldg_nm>
    <deal_ymd>
     20240130
    </deal_ymd>
    <obj_amt>
     40000
    </obj_amt>
    <bldg_area>
     69.13
    </bldg_area>
    <tot_area>
     48.370000
    </tot_area>
    <floor>
     3
    </floor>
    <right_gbn>
    </right_gbn>
    <cntl_ymd>
    </cntl_ymd>
    <build_year>
     1991
    </build_year>
    <house_type>
     연립다세대
    </house_type>
    <req_gbn>
     중개거래
    </req_gbn>
    <rdealer_lawdnm>
     서울 강남구
    </rdealer_lawdnm>
   </row>
  </tblnopendatartmsv>
 </body>
</html>

C:\Users\user\AppData\Local\Temp\ipykernel_16988\2197614523.py:6: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  soup = BeautifulSoup(req.content, 'lxml')

In [18]:
years            = soup.find_all('acc_year')         # 접수년월
sgg_cds          = soup.find_all('sgg_cd')           # 자치구코드
sgg_nms          = soup.find_all('sgg_nm')           # 자치구명
bjdong_cds       = soup.find_all('bjdong_cd')        # 법정동코드
bjdong_nms       = soup.find_all('bjdong_nm')        # 법정동명
land_gbns        = soup.find_all('land_gbn')         # 지번구분
land_gbn_nms     = soup.find_all('land_gbn_nm')      # 지번구분명
land_gbn_nms     = soup.find_all('land_gbn_nm')      # 지번구분명
bonbeons         = soup.find_all('bonbeon')          # 본번
bubeons          = soup.find_all('bubeon')           # 부번
bldg_nms         = soup.find_all('bldg_nm')          # 건물명
deal_ymds        = soup.find_all('deal_ymd')         # 계약일
obj_amts         = soup.find_all('obj_amt')          # 물건금액(만원)
bldg_areas       = soup.find_all('bldg_area')        # 건물면적(㎡)
tot_areas        = soup.find_all('tot_area')         # 토지면적(㎡)
floors           = soup.find_all('floor')            # 층
right_gbns       = soup.find_all('right_gbn')        # 권리구분
cntl_ymds        = soup.find_all('cntl_ymd')         # 취소일
build_years      = soup.find_all('build_years')      # 건축년도
house_types      = soup.find_all('house_type')       # 건물용도
req_gbn          = soup.find_all('req_gbn')          # 신고구분
rdealer_lawdnms  = soup.find_all('rdealer_lawdnm')   # 신고한 개업공인중개사 시군구명

year_list           = []
sgg_cd_list         = []
bldg_nm_list        = []
obj_amt_list        = []
house_type_list     = []
rdealer_lawdnm_list = []

for year, sgg_cd, bldg_nm, obj_amt, house_type, rdealer_lawdnm in zip(years, sgg_cds, bldg_nms, obj_amts, house_types, rdealer_lawdnms):
  year_list.append(year.get_text())
  sgg_cd_list.append(sgg_cd.get_text())
  bldg_nm_list.append(bldg_nm.get_text())
  obj_amt_list.append(obj_amt.get_text())
  house_type_list.append(house_type.get_text())
  rdealer_lawdnm_list.append(rdealer_lawdnm.get_text())

df = pd.DataFrame({
    "acc_year": year_list, 
    "sgg_cd": sgg_cd_list, 
    "bldg_nm" : bldg_nm_list,
    "obj_amt": obj_amt_list,
    "house_type" : house_type_list,
    "rdealer_lawdnm": rdealer_lawdnm_list
})

df

  acc_year sgg_cd    bldg_nm obj_amt house_type rdealer_lawdnm
0     2024  11560   여의도리슈빌DS   20600       오피스텔        서울 영등포구
1     2024  11740       도우빌라   36700      연립다세대         서울 강동구
2     2024  11320   중흥에스-클래스   55000        아파트         서울 도봉구
3     2024  11545  중앙하이빌1동2동   23000      연립다세대
4     2024  11590      종로빌리지   40000      연립다세대         서울 강남구

## 공공데이터 포털
- 국토교통부

In [11]:
import requests 
import json 
import pandas as pd 
import xmltodict

PUBLIC_SERVICE_KEY = 'SDEjyCFJI1ki5hZaMAvBGUsre6U38rZKkVug%2BDGju9aAUp9G7%2B1tQagaeWcG2trJmx1%2BXe0JANCSgpGnLFuOPA%3D%3D'

# serviceKey = '인증키 입력'
pageNo = 1 # 페이지 번호
numOfRows = 500 # 한 페이지 결과수
LAWD_CD = 11500 # 지역코드
DEAL_YMD = 202101 # 계약월
url = f'http://openapi.molit.go.kr/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTradeDev?serviceKey={PUBLIC_SERVICE_KEY}&pageNo={pageNo}&numOfRows={numOfRows}&LAWD_CD={LAWD_CD}&DEAL_YMD={DEAL_YMD}'
req = requests.get(url)

# req.text
contents = xmltodict.parse(req.text)
data = pd.DataFrame(contents['response']['body']['items']['item'])
data.head()

,거래금액,거래유형,건축년도,년,도로명,도로명건물본번호코드,도로명건물부번호코드,도로명시군구코드,도로명일련번호코드,도로명지상지하코드,...,월,일,일련번호,전용면적,중개사소재지,지번,지역코드,층,해제사유발생일,해제여부
0,"70,000",None,1996,2021,양천로75길,00060,00000,11500,01,0,...,1,3,11500-30,59.92,None,291,11500,12,None,None
1,"85,500",None,1992,2021,양천로67길,00054,00000,11500,01,0,...,1,5,11500-23,84.7,None,287-1,11500,12,None,None
2,"98,000",None,2005,2021,공항대로,00637,00000,11500,01,0,...,1,5,11500-5104,84.84,None,282-19,11500,4,None,None
3,"80,300",None,1994,2021,양천로75길,00057,00000,11500,01,0,...,1,5,11500-28,84.34,None,288,11500,2,None,None
4,"74,800",None,1995,2021,양천로,00637,00000,11500,01,0,...,1,6,11500-16,59.94,None,244-2,11500,7,None,None

## 다중 데이터 수집

In [10]:
i = 5
1 + (i-1) * 1000, i * 1000

(4001, 5000)

In [16]:
import requests
import pandas as pd 
SERVICE_KEY = '78577a466b6a686a3539434662496e'

# 네이버 주식 차트 pd.concat()
data = None
for j in range(1,3):
    url = f'http://openapi.seoul.go.kr:8088/{SERVICE_KEY}/json/tbLnOpendataRtmsV/{1+((j-1)*1000)}/{j*1000}'
    # url = f'http://openapi.seoul.go.kr:8088/{service_key}/json/tbLnOpendataRentV/1/1000/2023/11560'
    print(url)
    req = requests.get(url)
    content = req.json()
    con = content['tbLnOpendataRtmsV']['row']
    result = pd.DataFrame(con)
    data = pd.concat([data, result])
data = data.reset_index(drop=True)
data.head()

http://openapi.seoul.go.kr:8088/78577a466b6a686a3539434662496e/json/tbLnOpendataRtmsV/1/1000
http://openapi.seoul.go.kr:8088/78577a466b6a686a3539434662496e/json/tbLnOpendataRtmsV/1001/2000

,ACC_YEAR,SGG_CD,SGG_NM,BJDONG_CD,BJDONG_NM,LAND_GBN,LAND_GBN_NM,BONBEON,BUBEON,BLDG_NM,...,OBJ_AMT,BLDG_AREA,TOT_AREA,FLOOR,RIGHT_GBN,CNTL_YMD,BUILD_YEAR,HOUSE_TYPE,REQ_GBN,RDEALER_LAWDNM
0,2024,11560,영등포구,10200,영등포동1가,1,대지,0121,0005,여의도리슈빌DS,...,20600,21.41,31.43,7.0,,,2020,오피스텔,중개거래,서울 영등포구
1,2024,11740,강동구,10900,천호동,1,대지,0090,0002,도우빌라,...,36700,48.69,46.66,-1.0,,,1991,연립다세대,중개거래,서울 강동구
2,2024,11320,도봉구,10800,도봉동,1,대지,0051,0012,중흥에스-클래스,...,55000,85.00,0.00,3.0,,,2004,아파트,중개거래,서울 도봉구
3,2024,11545,금천구,10200,독산동,1,대지,1006,0115,중앙하이빌1동2동,...,23000,28.68,14.88,4.0,,,2016,연립다세대,직거래,
4,2024,11590,동작구,10300,상도1동,1,대지,0419,0003,종로빌리지,...,40000,69.13,48.37,3.0,,,1991,연립다세대,중개거래,서울 강남구

In [17]:
data

,ACC_YEAR,SGG_CD,SGG_NM,BJDONG_CD,BJDONG_NM,LAND_GBN,LAND_GBN_NM,BONBEON,BUBEON,BLDG_NM,...,OBJ_AMT,BLDG_AREA,TOT_AREA,FLOOR,RIGHT_GBN,CNTL_YMD,BUILD_YEAR,HOUSE_TYPE,REQ_GBN,RDEALER_LAWDNM
0,2024,11560,영등포구,10200,영등포동1가,1,대지,0121,0005,여의도리슈빌DS,...,20600,21.41,31.43,7.0,,,2020,오피스텔,중개거래,서울 영등포구
1,2024,11740,강동구,10900,천호동,1,대지,0090,0002,도우빌라,...,36700,48.69,46.66,-1.0,,,1991,연립다세대,중개거래,서울 강동구
2,2024,11320,도봉구,10800,도봉동,1,대지,0051,0012,중흥에스-클래스,...,55000,85.00,0.00,3.0,,,2004,아파트,중개거래,서울 도봉구
3,2024,11545,금천구,10200,독산동,1,대지,1006,0115,중앙하이빌1동2동,...,23000,28.68,14.88,4.0,,,2016,연립다세대,직거래,
4,2024,11590,동작구,10300,상도1동,1,대지,0419,0003,종로빌리지,...,40000,69.13,48.37,3.0,,,1991,연립다세대,중개거래,서울 강남구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,2024,11440,마포구,12500,성산동,1,대지,0590,0001,상암 두산위브센티움,...,16500,23.69,33.77,8.0,,,2013,오피스텔,중개거래,서울 마포구
1996,2024,11440,마포구,12500,성산동,1,대지,0592,0008,마포클레세,...,20500,20.53,33.01,8.0,,,2022,오피스텔,직거래,
1997,2024,11305,강북구,10300,수유동,1,대지,0410,0141,동아하이츠빌라,...,16300,40.32,25.47,1.0,,,1994,연립다세대,중개거래,서울 강북구
1998,2024,11560,영등포구,13200,신길동,1,대지,4955,0000,신길센트럴아이파크,...,102000,59.97,0.00,12.0,,,2019,아파트,중개거래,서울 영등포구
1999,2024,11380,은평구,11400,진관동,1,대지,0009,0000,은평지웰테라스,...,78250,84.31,97.73,2.0,,,2017,연립다세대,중개거래,서울 은평구